/**
 * Every MCP tool's output schema, by tool name: the one list both the registry (which checks
 * each tool declares exactly this schema) and the chat UI's `StructuredToolOutput` derive from.
 */
import {
	CreateAlertRuleOutput,
	DeleteAlertRuleOutput,
	GetAlertRuleOutput,
	GetIncidentTimelineOutput,
	ListAlertChecksOutput,
	ListAlertDestinationsOutput,
	ListAlertIncidentsOutput,
	ListAlertRulesOutput,
	UpdateAlertRuleOutput,
} from "./alerts"
import {
	AddDashboardWidgetOutput,
	CreateDashboardOutput,
	DescribeDashboardSchemaOutput,
	GetDashboardOutput,
	InspectChartDataOutput,
	ListDashboardsOutput,
	RemoveDashboardWidgetOutput,
	ReorderDashboardWidgetsOutput,
	ReplaceDashboardWidgetsOutput,
	UpdateDashboardOutput,
	UpdateDashboardWidgetOutput,
} from "./dashboards"
import { ErrorDetailOutput, FindErrorsOutput } from "./errors"
import {
	ClaimErrorIssueOutput,
	CommentOnErrorIssueOutput,
	LinkPullRequestOutput,
	ListErrorIncidentsOutput,
	ListErrorIssueEventsOutput,
	ListErrorIssuesOutput,
	ProposeFixOutput,
	RegisterAgentOutput,
	ReleaseErrorIssueOutput,
	SetIssueSeverityOutput,
	TransitionErrorIssueOutput,
	UpdateErrorNotificationPolicyOutput,
} from "./issues"
import {
	ComparePeriodsOutput,
	DescribeWarehouseTablesOutput,
	DiagnoseServiceOutput,
	ExploreAttributesOutput,
	GetServiceTopOperationsOutput,
	ListMetricsOutput,
	ListServicesOutput,
	QueryDataOutput,
	RunSqlOutput,
	ServiceMapOutput,
} from "./services"
import {
	GetAgentSessionOutput,
	GetAgentToolErrorOutput,
	GetAgentToolsOverviewOutput,
	GetSessionTracesOutput,
	GetSessionTranscriptOutput,
	ListAgentSessionsOutput,
	ListProductEventsOutput,
	QueryFunnelOutput,
	SearchSessionsOutput,
} from "./sessions"
import {
	AuditSetupOutput,
	GetInstrumentationRecommendationsOutput,
	ListSourceRepositoriesOutput,
	PrChangedFilesOutput,
	PrContextOutput,
	PrFileDiffOutput,
	ReadSourceFileOutput,
	SandboxExecOutput,
	SandboxGrepOutput,
	SandboxListFilesOutput,
	SandboxReadFileOutput,
	SearchSourceCodeOutput,
} from "./setup"
import {
	FindSlowTracesOutput,
	InspectSpanOutput,
	InspectTraceOutput,
	MineLogPatternsOutput,
	SearchLogsOutput,
	SearchTracesOutput,
} from "./traces"

export const McpToolOutputs = {
	add_dashboard_widget: AddDashboardWidgetOutput,
	audit_setup: AuditSetupOutput,
	claim_error_issue: ClaimErrorIssueOutput,
	comment_on_error_issue: CommentOnErrorIssueOutput,
	compare_periods: ComparePeriodsOutput,
	create_alert_rule: CreateAlertRuleOutput,
	create_dashboard: CreateDashboardOutput,
	delete_alert_rule: DeleteAlertRuleOutput,
	describe_dashboard_schema: DescribeDashboardSchemaOutput,
	describe_warehouse_tables: DescribeWarehouseTablesOutput,
	diagnose_service: DiagnoseServiceOutput,
	error_detail: ErrorDetailOutput,
	explore_attributes: ExploreAttributesOutput,
	find_errors: FindErrorsOutput,
	find_slow_traces: FindSlowTracesOutput,
	get_agent_session: GetAgentSessionOutput,
	get_agent_tool_error: GetAgentToolErrorOutput,
	get_agent_tools_overview: GetAgentToolsOverviewOutput,
	get_alert_rule: GetAlertRuleOutput,
	get_dashboard: GetDashboardOutput,
	get_incident_timeline: GetIncidentTimelineOutput,
	get_instrumentation_recommendations: GetInstrumentationRecommendationsOutput,
	get_service_top_operations: GetServiceTopOperationsOutput,
	get_session_traces: GetSessionTracesOutput,
	get_session_transcript: GetSessionTranscriptOutput,
	inspect_chart_data: InspectChartDataOutput,
	inspect_span: InspectSpanOutput,
	inspect_trace: InspectTraceOutput,
	link_pull_request: LinkPullRequestOutput,
	list_agent_sessions: ListAgentSessionsOutput,
	list_alert_checks: ListAlertChecksOutput,
	list_alert_destinations: ListAlertDestinationsOutput,
	list_alert_incidents: ListAlertIncidentsOutput,
	list_alert_rules: ListAlertRulesOutput,
	list_dashboards: ListDashboardsOutput,
	list_error_incidents: ListErrorIncidentsOutput,
	list_error_issue_events: ListErrorIssueEventsOutput,
	list_error_issues: ListErrorIssuesOutput,
	list_metrics: ListMetricsOutput,
	list_product_events: ListProductEventsOutput,
	list_services: ListServicesOutput,
	list_source_repositories: ListSourceRepositoriesOutput,
	mine_log_patterns: MineLogPatternsOutput,
	pr_changed_files: PrChangedFilesOutput,
	pr_context: PrContextOutput,
	pr_file_diff: PrFileDiffOutput,
	propose_fix: ProposeFixOutput,
	query_data: QueryDataOutput,
	query_funnel: QueryFunnelOutput,
	read_source_file: ReadSourceFileOutput,
	register_agent: RegisterAgentOutput,
	release_error_issue: ReleaseErrorIssueOutput,
	remove_dashboard_widget: RemoveDashboardWidgetOutput,
	reorder_dashboard_widgets: ReorderDashboardWidgetsOutput,
	replace_dashboard_widgets: ReplaceDashboardWidgetsOutput,
	run_sql: RunSqlOutput,
	sandbox_exec: SandboxExecOutput,
	sandbox_grep: SandboxGrepOutput,
	sandbox_list_files: SandboxListFilesOutput,
	sandbox_read_file: SandboxReadFileOutput,
	search_logs: SearchLogsOutput,
	search_sessions: SearchSessionsOutput,
	search_source_code: SearchSourceCodeOutput,
	search_traces: SearchTracesOutput,
	service_map: ServiceMapOutput,
	set_issue_severity: SetIssueSeverityOutput,
	transition_error_issue: TransitionErrorIssueOutput,
	update_alert_rule: UpdateAlertRuleOutput,
	update_dashboard: UpdateDashboardOutput,
	update_dashboard_widget: UpdateDashboardWidgetOutput,
	update_error_notification_policy: UpdateErrorNotificationPolicyOutput,
} as const

export type McpToolName = keyof typeof McpToolOutputs
