import { createHash } from "node:crypto"
import type { SchemaDefinitionError } from "@maple-dev/effect-orm/schema"
import { buildProject, type Datafile } from "@maple-dev/effect-orm/tinybird"
import { Effect } from "effect"
import * as Datasources from "./datasources"
import * as Materializations from "./materializations"

export type GeneratedResource = Datafile

export interface TinybirdProjectManifest {
	readonly projectRevision: string
	readonly datasources: ReadonlyArray<GeneratedResource>
	readonly pipes: ReadonlyArray<GeneratedResource>
}

export const createTinybirdProjectRevision = (
	datasources: ReadonlyArray<GeneratedResource>,
	pipes: ReadonlyArray<GeneratedResource>,
): string => {
	const digest = createHash("sha256")

	for (const resource of [...datasources].sort((left, right) => left.name.localeCompare(right.name))) {
		digest.update(`datasource:${resource.name}\n${resource.content}\n`)
	}

	for (const resource of [...pipes].sort((left, right) => left.name.localeCompare(right.name))) {
		digest.update(`pipe:${resource.name}\n${resource.content}\n`)
	}

	return digest.digest("hex")
}

export const buildTinybirdProjectManifest: Effect.Effect<TinybirdProjectManifest, SchemaDefinitionError> =
	Effect.map(buildProject(Datasources, Materializations), ({ datasources, pipes }) => ({
		datasources,
		pipes,
		projectRevision: createTinybirdProjectRevision(datasources, pipes),
	}))

export const renderTinybirdProjectManifestModule = (manifest: TinybirdProjectManifest): string => {
	const datasources = JSON.stringify(manifest.datasources, null, 2)
	const pipes = JSON.stringify(manifest.pipes, null, 2)

	return `// This file is generated by scripts/generate-tinybird-project-manifest.ts
// Do not edit manually.

export const projectRevision = ${JSON.stringify(manifest.projectRevision)} as const

export const datasources = ${datasources} as const

export const pipes = ${pipes} as const

export const tinybirdProjectManifest = {
  projectRevision,
  datasources,
  pipes,
} as const
`
}
