#!/usr/bin/env bun
/**
 * `bun run seed:demo:env`: set up the isolated screenshot stack.
 *
 * Creates and migrates a `maple_screenshots` Postgres database next to the dev
 * one, then writes `.env.screenshots`: `.env.local` pinned to the demo org, on
 * that database, with the static ingest key store and the alerting crons on.
 * The crons only ever see the demo org's rules, so the seeded incident never
 * pages a real destination. Run the stack with
 * `MAPLE_DEV_ENV_FILE=.env.screenshots bun dev api web ingest alerting`.
 */
import { NodeRuntime, NodeServices } from "@effect/platform-node"
import { Console, Effect, FileSystem, Schema } from "effect"
import { ChildProcess, ChildProcessSpawner } from "effect/process"

export const DEMO_ORG_ID = "org_3AcmeShopDemo0000000000000"
const DATABASE = "maple_screenshots"
const ROOT = new URL("../../", import.meta.url).pathname

class MakeEnvError extends Schema.TaggedError<MakeEnvError>()("@maple/seed-demo/MakeEnvError", {
	message: Schema.String,
}) {}

// Explicit values only: mise loads `.env.local` into the shell, so a dropped key would still be inherited.
const OVERRIDES = new Map([
	["MAPLE_ORG_ID_OVERRIDE", DEMO_ORG_ID],
	["MAPLE_ALERTING_ALLOW_NONPROD", "1"],
	// Any maple_pk_* key resolves to the demo org.
	["INGEST_KEY_STORE_BACKEND", "static"],
	// Billing off: the plan gate fails open and no test customer lands in the Autumn sandbox.
	["AUTUMN_SECRET_KEY", ""],
	// The web app's own browser telemetry would otherwise land in the demo org.
	["MAPLE_OTEL_PUBLIC_INGEST_KEY", ""],
	["VITE_MAPLE_INGEST_KEY", ""],
])

/** Point the URL at the screenshot database, also when it names none or ends in a slash. */
const withDatabase = (url: string) =>
	Effect.try({
		try: () => {
			const parsed = new URL(url)
			parsed.pathname = `/${DATABASE}`
			return parsed.toString()
		},
		catch: () => new MakeEnvError({ message: "MAPLE_PG_URL in .env.local is not a valid URL" }),
	})

const program = Effect.gen(function* () {
	const fs = yield* FileSystem.FileSystem
	const spawner = yield* ChildProcessSpawner.ChildProcessSpawner
	const source = yield* fs.readFileString(`${ROOT}.env.local`)

	const pgLine = source.split("\n").find((line) => line.startsWith("MAPLE_PG_URL="))
	if (pgLine === undefined) return yield* new MakeEnvError({ message: ".env.local has no MAPLE_PG_URL" })
	const devUrl = pgLine.slice("MAPLE_PG_URL=".length).trim()
	const demoUrl = yield* withDatabase(devUrl)

	const exists = yield* spawner.string(
		ChildProcess.make("psql", [
			devUrl,
			"-tAc",
			`SELECT 1 FROM pg_database WHERE datname = '${DATABASE}'`,
		]),
	)
	if (exists.trim() !== "1") {
		yield* spawner.string(ChildProcess.make("psql", [devUrl, "-c", `CREATE DATABASE ${DATABASE}`]))
		yield* Console.log(`created database ${DATABASE}`)
	}
	yield* spawner.string(
		ChildProcess.make("bun", ["run", "db:migrate"], {
			cwd: `${ROOT}packages/db`,
			env: { DATABASE_URL: demoUrl },
			extendEnv: true,
		}),
		{ includeStderr: true },
	)
	yield* Console.log(`migrated ${DATABASE}`)

	const seen = new Set<string>()
	const lines = source.split("\n").flatMap((line) => {
		const key = /^([A-Z0-9_]+)=/.exec(line)?.[1]
		if (key === "MAPLE_PG_URL") return [`MAPLE_PG_URL=${demoUrl}`]
		if (key === undefined || !OVERRIDES.has(key)) return [line]
		seen.add(key)
		return [`${key}=${OVERRIDES.get(key)}`]
	})
	const added = [...OVERRIDES].flatMap(([key, value]) => (seen.has(key) ? [] : [`${key}=${value}`]))
	// Copies .env.local's secrets, so owner-only; chmod covers a file an older run created.
	const envPath = `${ROOT}.env.screenshots`
	yield* fs.writeFileString(
		envPath,
		[
			`# Generated by bun run seed:demo:env from .env.local. Do not edit; re-run instead.`,
			...lines,
			...added,
		].join("\n"),
		{ mode: 0o600 },
	)
	yield* fs.chmod(envPath, 0o600)
	yield* Console.log(`wrote .env.screenshots (org ${DEMO_ORG_ID}, database ${DATABASE})`)
})

// oxlint-disable-next-line effecttsgo/strict-effect-provide
program.pipe(Effect.provide(NodeServices.layer), NodeRuntime.runMain)
